AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/update'
    - 'bin/setup'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false
