version: '3.6'
services:
  db:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web: &rails_base
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid &&
                         bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    links:
      - db
    depends_on:
      - db

  spring:
    <<: *rails_base
    command: bundle exec spring server
    ports: []
    tty: false
    stdin_open: false

volumes:
  postgres_data:
  bundle:
  node_modules:
